# Generated by Django 5.0.4 on 2024-04-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante_pk2025',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('admitido', 'Admitido'), ('lista_espera', 'Lista de Espera'), ('no_admitido', 'No Admitido'), ('desistido', 'Desistido')], max_length=20)),
                ('motivo_desistimiento', models.TextField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], max_length=10)),
                ('posicion_lista_espera', models.IntegerField(blank=True, null=True)),
                ('colegio_alternativo', models.CharField(blank=True, choices=[('colegio1', 'Colegio 1'), ('colegio2', 'Colegio 2'), ('colegio3', 'Colegio 3'), ('colegio4', 'Colegio 4'), ('colegio5', 'Colegio 5')], max_length=20, null=True)),
                ('confirmacion', models.BooleanField(default=False)),
            ],
        ),
    ]
