# Generated by Django 5.0.4 on 2024-04-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes01', '0003_alter_postulante_pk2025_confirmacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante_pk2025',
            name='confirmacion',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('negado', 'Negado'), ('sin_confirmar', 'Sin Confirmar')], default='sin_confirmar', max_length=20),
        ),
    ]
