# Generated by Django 5.0.4 on 2024-04-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes01', '0004_alter_postulante_pk2025_confirmacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante_pk2025',
            name='colegio_alternativo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postulante_pk2025',
            name='confirmacion',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('negado', 'Negado'), ('', '')], default='', max_length=20),
        ),
    ]
